# docker-compose.yml

version: "3.7"

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/media/
    env_file:
      - project_config/.env.postgres
    networks:
      - second
    ports:
      - "5433:5432"
    restart: always

  pgbackups:
    container_name: pgbackups
    hostname: pgbackups
    image: prodrigestivill/postgres-backup-local
    volumes:
      - ./backups:/backups
    env_file:
      - project_config/.env.postgres
    user: postgres:postgres
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - second
    restart: always

  web:
    container_name: web
    hostname: web
    build: back
    image: web-image
    command: sh -c "python manage.py makemigrations&& python manage.py migrate&& python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back/static:/home/app/web/static
      - ./back/media:/home/app/web/media
      - ./back:/home/app/web
    env_file:
      - project_config/.env.back
    depends_on:
      - postgres
    networks:
      - second
    ports:
      - "8000:8000"
    restart: always

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back/static:/home/app/web/static
      - ./back/media:/home/app/web/media
    depends_on:
      - web
    networks:
      - second
    ports:
      - "5000:5000"
    restart: always

networks:
  second:
    name: second
#    external: true
#    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
